---
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install yamllint
  pre_build:
    commands:
      - yamllint cloudformation.yml .yamllint .s8/*.yml
  build:
    commands:
      - virtualenv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
      - zappa package production -o App.zip

artifacts:
  files:
    - cloudformation.yml
    - App.cf.json
    - App.zip
